#! /usr/bin/env bash
# Initialize shell from files in ~/profile.d
# Order matters
# Change file extension from .sh to skip on startup
if [[ -d "$HOME/profile.d" ]]; then
    for file in "$HOME/profile.d"/*.sh; do
        # If the file name contains "-shell-", skip it in .zshenv
        if [[ "$file" == *-shell-* ]]; then
            continue
        fi
        # shellcheck source=/dev/null
        [[ -r "$file" ]] && . "$file"
    done
    unset file
fi
