version: '3'

# Run this file with [go-task](https://taskfile.dev/).
# Tasks refresh global tooling.

tasks:
  brew:
    desc: Update versions of brew packages with brew update
    cmds:
      - brew upgrade

  fnm-lts:
    desc: Update Node LTS versions via fnm
    preconditions:
      - sh: command -v fnm
        msg: "bun is not installed so no updates to perform"
    cmds:
      - fnm install lts/jod
      - fnm install lts/krypton
      - fnm install lts/latest
      - fnm default lts/krypton
      - fnm use default

  bun-global:
    desc: Update versions of global CLIs installed via bun
    preconditions:
      - sh: command -v bun
        msg: "bun is not installed so no updates to perform"
    dir: ~/.bun/install/global
    cmd: bun install

  uv-tool:
    desc: Upgrade all tools installed via uv tool
    preconditions:
      - sh: command -v uv
        msg: "uv is not installed so no updates to perform"
    cmd: uv tool upgrade --all

  hermes:
    desc: Upgrade the hermes agent
    preconditions:
      - sh: command -v hermes
        msg: "hermes is not installed so no updates to perform"
    cmd: hermes update
    
  all:
    desc: Default update sequence for Forge Rovo agents
    cmds:
      - echo "brew"
      - task: brew
      - echo "fnm-lts"
      - task: fnm-lts
      - echo "bun-global"
      - task: bun-global
      - echo "uv-tool"
      - task: uv-tool
      - echo "hermes"
      - task: hermes
