version: "3"

# Run this file with [go-task](https://taskfile.dev/).
# Tasks refresh global tooling.

includes:
  update: ./updates.yml

tasks:
  all:
    desc: Default update sequence
    cmds:
      - for: [brew, fnm-lts, bun-global, uv-tool, ccc-restart, twg-cli, hermes]
        task: update:{{.ITEM}}
